### ISSUE TITLE
Could not find method runProGuard()

### ISSUE THREAD

**Issue by Syedwaheed** [MobiDevelop/android-split-pane-layout#12]
Error:(16, 0) Could not find method runProguard() for arguments [false] on BuildType_Decorated{name=release, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=null, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.

**Comment by MobiDevelop** [comment]
You must have updated the Gradle plugin version. To resolve you'll need to change `runProguard false` to `minifyEnabled false`
