### ISSUE TITLE
Is this usable within a fragment?

### ISSUE THREAD

**Issue by csolorio** [MobiDevelop/android-split-pane-layout#16]
Hi, there. 

Experimenting a bit with this layout, using it as the parent element of a fragment crashes the app in runtime... With no error message at all in the debugging window in Android Studio. The error occurs in the onCreateView fragment event, when the "inflate" method is invoked.

I'm using kotlin, Android Studio 3.3, androidx, gradle 3.3... Also, on kotlin, a SplitPaneLayout object... There's some kind of issue with "onSplitterPositionChangedListener"... Can't be resolved...

Any idea?

**Comment by csolorio** [comment]
I compared the main class source file from the github project against the downloaded version from maven/gradle... And they're too different. That's the cause of the listener not present error that I mentioned above...

**Comment by csolorio** [comment]
Ok, I discarded completely the version that is uploaded in mavencentral, used the one in github and works as expected! It's sad not to use gradle though...

**Comment by MobiDevelop** [comment]
I'll try to get Maven Central updated with the latest version soon.
